# Generated by Django 4.0.3 on 2022-04-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(),
        ),
    ]
